linter:
  robotframework:
    enabled: true
    language: "python"
    lint_command: "robocop --disable-all --enable-all"
cspell:
  enabled: true
  ignoreWords:
    - robotframework
    - robocop
    - SARIF


