name: Linter

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: MegaLinter
        uses: oxsecurity/megalinter/flavors/python@v8.4.2