name: Linter

permissions:
  contents: read  # Read access to the repository
  pull-requests: write  # Write access to pull requests (if needed)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    # continue even if Robocop returns issues and fails step
    continue-on-error: true
    permissions:
      # required for issues to be recorded
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework-robocop
      - name: Run robocop
        run: python -m robocop --reports sarif .
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: .sarif.json
          category: robocop
