name: Robot Framework Linting and Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  robocop-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework-robocop

      - name: Run Robocop Linting
        run: |
          robot --version  # Ensure Robot Framework is installed
          robocop --output sarif --reports robocop-report.html tests/
        # Adjust 'tests/' to the folder where your Robot Framework test files are located

      - name: Upload SARIF report (Optional)
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: robocop-report.sarif
