name: Linter

permissions:
  contents: read  # Read access to the repository
  pull-requests: write  # Write access to pull requests (if needed)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: MegaLinter
        uses: oxsecurity/megalinter/flavors/python@v8.4.2

      - name: robocop
        uses: python -m robocop --reports sarif .

      - name: Install dependencies
        run: python -m pip install --upgrade pip
          pip install robotframework-robocop
