name: MegaLinter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Make sure it’s Python 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework-robocop  # Install robocop

      - name: Install MegaLinter
        run: |
          npm install -g mega-linter-runner

      - name: Run MegaLinter
        run: |
          mega-linter-runner

